const db = require("../util/database");

const Cart = require("./cart");

module.exports = class Product {
  constructor(id, title, imageUrl, price, description) {
    this.id = id;
    this.title = title;
    this.price = price;
    this.imageUrl = imageUrl;
    this.description = description;
  }

  save() {
    return db.execute(
      "INSERT INTO products (title, price, imageUrl, description) VALUES (?,?,?,?)", // the id is auto-generated by the db
      [this.title, this.price, this.imageUrl, this.description]
    );
  }

  static deleteById(id) {}

  static fetchAll() {
    // products is all fields not rows
    return db.execute("SELECT * FROM products");
  }
  static findById(id) {
    // in a db, no need to read all pdts, just query pdt by id
    return db.execute("SELECT * FROM products WHERE products.id = ?", [id]);
  }
};
